### ISSUE TITLE
interface conversion: *negroni.responseWriterCloseNotifer is not negroni.ResponseWrite

### ISSUE THREAD

**Issue by mg03** [urfave/negroni#159]
Hi

Im using go version 1.7.4 on mac os

Im am getting following error

```
2016/12/02 19:32:22 http: panic serving [::1]:59323: interface conversion: *negroni.responseWriterCloseNotifer is not negroni.ResponseWriter: missing method Before
goroutine 34 [running]:
net/http.(*conn).serve.func1(0xc82010c000)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:1389 +0xc1
panic(0x387e00, 0xc8201042c0)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
github.com/meatballhat/negroni-logrus.(*Middleware).ServeHTTP(0xc82009c360, 0x1180248, 0xc82010a008, 0xc820124000, 0xc8201161a0)
	/Users/go_workspace/usher/vendor/src/github.com/meatballhat/negroni-logrus/middleware.go:138 +0x61c
github.com/codegangsta/negroni.middleware.ServeHTTP(0x1144710, 0xc82009c360, 0xc820116140, 0x1180248, 0xc82010a008, 0xc820124000)
	/Users/go_workspace/usher/vendor/src/github.com/codegangsta/negroni/negroni.go:33 +0xaa
github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc820108150, 0x1180160, 0xc820128000, 0xc820124000)
	/Users/go_workspace/usher/vendor/src/github.com/codegangsta/negroni/negroni.go:73 +0x1a6
github.com/carbocation/interpose/adaptors.FromNegroni.func1.1(0x1180160, 0xc820128000, 0xc820124000)
	/Users/go_workspace/usher/vendor/src/github.com/carbocation/interpose/adaptors/negroni.go:15 +0x3e
net/http.HandlerFunc.ServeHTTP(0xc820118070, 0x1180160, 0xc820128000, 0xc820124000)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:1618 +0x3a
github.com/carbocation/interpose.(*Middleware).ServeHTTP(0xc8200d4820, 0x1180160, 0xc820128000, 0xc820124000)
	/Users/go_workspace/usher/vendor/src/github.com/carbocation/interpose/interpose.go:85 +0x6c
net/http.serverHandler.ServeHTTP(0xc82007e180, 0x1180160, 0xc820128000, 0xc820124000)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82010c000)
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.6.2/libexec/src/net/http/server.go:2137 +0x44e
```

**Comment by gravis** [comment]
> usher/vendor/src/github.com/codegangsta/negroni

You should use the urfave repo, and make sure you're up to date first. Thanks

**Comment by mg03** [comment]
@gravis : i got it while doing gb vendor fetch interpose ..... i guess interpose is using usher/vendor/src/github.com/codegangsta/negroni ..... let me try to fetch latest one

thanx

**Comment by gravis** [comment]
Any news on this? :)

**Comment by gravis** [comment]
I think we can safely close this, as the bug has been identified in the interpose project instead.

**Comment by gravis** [comment]
Interpose has been updated:
https://github.com/carbocation/interpose/pull/12#event-884361421
Can you please update your dep, and tell me if everything is ok now?
Thanks

**Comment by mg03** [comment]
ok .. i will try but please close issue for now

**Comment by jszwedko** [comment]
:+1: thanks for finding that @gravis 

Closing since this appeared to be an out-of-date dependency issue.
